server:
  port: 8079

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/product
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/order/create
          - id: inventory-service
            uri: lb://inventory-service
            predicates:
              - Path=/inventory/get
          - id: discovery-service
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/web
            filters:
            - SetPath=/
          - id: discovery-service-static
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/**
