spring:
  security:
    oauth2:
     resourceserver:
      jwt:
        issuer-uri: http://localhost:8180/realms/springboot-microservices
        jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs